### ISSUE TITLE
Unauthorized use of material.

### ISSUE THREAD

**Issue by JackCrispy** [CreationOfGenji/fivem-module#2]
Hi, I request you update your README or remove your NPM Package and Github repo.

This is copied from https://github.com/JackCrispy/fivem/ which according to my license, the GNU General Public License 3.0, states that you must link back to the source, it also states you must use the same License if copying the source. (https://github.com/JackCrispy/fivem/blob/master/LICENSE)

Please update or I will have to report this to GitHub.

**Comment by CreationOfGenji** [comment]
Hi, this was never meant really for anyone to really use so I apologize for copying your source.

I have added your GitHub repo at the bottom of the readme and added the GNU General Public License 3.0. Please let me know if there is anything else I should add/remove!
